owner: mstcl
repo: status
sites:
  - name: Lemmy
    url: $LE_URL
  - name: Piped (FE)
    url: $PFE_URL
  - name: Piped (BE)
    url: $PBE_URL
  - name: Git
    url: $GIT_URL
  - name: Blog
    url: $BLOG_URL
  - name: Matrix
    url: $MATRIX_URL
  - name: Slsk
    check: "tcp-ping"
    url: $SLSK_URL
    port: $SLSK_PORT
  - name: Wd
    url: $WD_URL
    expectedStatusCodes:
      - 200
      - 201
      - 401

status-website:
  cname: $MAIN_URL
  logoUrl: ""
  name: Status
  introTitle: "Uptime status for services running on BIM."
  css: "html, body { font-family: sans-serif !important }"

i18n:
  footer: ""

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
